### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sandrofhhealth** [pactumjs/pactumjs.github.io#21]
**Is your feature request related to a problem? Please describe.**
Please, add dark mode my eyes just hurt while reading.

**Comment by ASaiAnudeep** [comment]
Use this ticket to track migration to vitepress.

- support analytics
- support SEO

**Comment by ASaiAnudeep** [comment]
We have migrated [test-results-reporter ](https://test-results-reporter.github.io/)to vitepress. Will replicate the same with PactumJS Docs as well.

@leelaprasadv
