### ISSUE TITLE
reset headers info is missing

### ISSUE THREAD

**Issue by RajatBhardwaj007** [pactumjs/pactumjs.github.io#51]
hi. I am not able to find reset headers info anywhere. Basically let's say in my test file, I am doing, 

`request.setDefaultHeaders({
              'X-API-KEY': 'api_key',
            });`
            
 
and I want that after this file executes, this header gets reset. I tried with request.setDefaultHeaders({}) but that didn't help. I can see same header being populated in other test files.

**Comment by ASaiAnudeep** [comment]
You can delete an existing default header via - [removeDefaultHeaders](https://github.com/pactumjs/pactum/blob/master/src/exports/request.js#L56C3-L56C23)

I will update the docs, sometime this week.

**Comment by leelaprasadv** [comment]
Closing as @RajatBhardwaj007  update the docs https://github.com/pactumjs/pactumjs.github.io/pull/52
